<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sk</string>
		<string>yml</string>
	</array>
	<key>name</key>
	<string>Sk-ST3</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string></string>
			<key>end</key>
			<string></string> 
			<key>name</key>
			<string>skript.everything</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(game( |)mode|(|all )player(s|)|victim|attacker|sender|loop-player|loop-value|loop-index|loop-number|uuid|location|world|entit(y|ies)|console)</string>
					<key>name</key>
					<string>skript.playerobjects</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\t+|\s+)(loop-\w+)</string>
					<key>name</key>
					<string>skript.loopobjects</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\t+|\s+)((format|make|create) (a |)gui slot)</string>
					<key>name</key>
					<string>skript.gui</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bslot\b</string>
					<key>name</key>
					<string>skript.gui</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((| |-)arg(ument(s|)|s|))\b</string>
					<key>name</key>
					<string>skript.args</string>
				</dict>
				<dict>
					<key>match</key>
					<string>test</string>
					<key>name</key>
					<string>skript.logic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((\.)|(\?)|\!|\@|\$|\%|\&amp;(?![abcdefmnolrk0-9])|\,)</string>
					<key>name</key>
					<string>skript.logic</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\\|\/|\:\:|\:|\[|\]|\(|\)|\.|\[|\])</string>
					<key>name</key>
					<string>skript.borders</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( )(as|at|by|with)( )</string>
					<key>name</key>
					<string>skript.others</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(contain(s|)|has|have|is(n't|)|are(n't|)|does(n't| not|))\b</string>
					<key>name</key>
					<string>skript.operatortwo</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)0|\&lt;black\&gt;)</string>
					<key>name</key>
					<string>skript.color.0</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)1|\&lt;(blue|dark blue)\&gt;)</string>
					<key>name</key>
					<string>skript.color.1</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)2|\&lt;(green|dark green)\&gt;)</string>
					<key>name</key>
					<string>skript.color.2</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)3|\&lt;(cyan|aqua|dark cyan|dark aqua)\&gt;)</string>
					<key>name</key>
					<string>skript.color.3</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)4|\&lt;(red|dark red)\&gt;)</string>
					<key>name</key>
					<string>skript.color.4</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)5|\&lt;(purple|dark purple)\&gt;)</string>
					<key>name</key>
					<string>skript.color.5</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)6|\&lt;(orange|gold|dark yellow)\&gt;)</string>
					<key>name</key>
					<string>skript.color.6</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)7|\&lt;(grey|light grey|gray|light gray|silver)\&gt;)</string>
					<key>name</key>
					<string>skript.color.7</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)8|\&lt;(dark grey|dark gray)\&gt;)</string>
					<key>name</key>
					<string>skript.color.8</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)9|\&lt;(light blue)\&gt;)</string>
					<key>name</key>
					<string>skript.color.9</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)a|\&lt;(light green|lime|lime green)\&gt;)</string>
					<key>name</key>
					<string>skript.color.a</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)b|\&lt;(light cyan|light aqua)\&gt;)</string>
					<key>name</key>
					<string>skript.color.b</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)c|\&lt;(pink|light red)\&gt;)</string>
					<key>name</key>
					<string>skript.color.c</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)d|\&lt;(magenta|light purple)\&gt;)</string>
					<key>name</key>
					<string>skript.color.d</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)e|\&lt;(yellow|light yellow)\&gt;)</string>
					<key>name</key>
					<string>skript.color.e</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)f|\&lt;white\&gt;)</string>
					<key>name</key>
					<string>skript.color.f</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)l|\&lt;(bold|b)\&gt;)</string>
					<key>name</key>
					<string>skript.color.l</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)o|\&lt;(italics|italic|i)\&gt;)</string>
					<key>name</key>
					<string>skript.color.o</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)n|\&lt;(underlined|underline|u)\&gt;)</string>
					<key>name</key>
					<string>skript.color.n</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)m|\&lt;(strikethrough|strike|s)\&gt;)</string>
					<key>name</key>
					<string>skript.color.m</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)k|\&lt;magic\&gt;)</string>
					<key>name</key>
					<string>skript.color.k</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((&amp;|§)r|\&lt;(reset|r)\&gt;)</string>
					<key>name</key>
					<string>skript.color.r</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\"</string>
					<key>end</key>
					<string>(\"|\n)</string>
					<key>name</key>
					<string>skript.text</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>\%</string>
							<key>end</key>
							<string>(\%|\n)</string>
							<key>name</key>
							<string>skript.text.variable</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\'</string>
							<key>name</key>
							<string>skript.text.variable</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\{\@.*?\}</string>
							<key>name</key>
							<string>skript.text.options</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\|\||\%nl\%|\%newline\%)</string>
							<key>name</key>
							<string>skript.text.newline</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)0|\&lt;black\&gt;)</string>
							<key>name</key>
							<string>skript.color.0</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)1|\&lt;(blue|dark blue)\&gt;)</string>
							<key>name</key>
							<string>skript.color.1</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)2|\&lt;(green|dark green)\&gt;)</string>
							<key>name</key>
							<string>skript.color.2</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)3|\&lt;(cyan|aqua|dark cyan|dark aqua)\&gt;)</string>
							<key>name</key>
							<string>skript.color.3</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)4|\&lt;(red|dark red)\&gt;)</string>
							<key>name</key>
							<string>skript.color.4</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)5|\&lt;(purple|dark purple)\&gt;)</string>
							<key>name</key>
							<string>skript.color.5</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)6|\&lt;(orange|gold|dark yellow)\&gt;)</string>
							<key>name</key>
							<string>skript.color.6</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)7|\&lt;(grey|light grey|gray|light gray|silver)\&gt;)</string>
							<key>name</key>
							<string>skript.color.7</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)8|\&lt;(dark grey|dark gray)\&gt;)</string>
							<key>name</key>
							<string>skript.color.8</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)9|\&lt;(light blue)\&gt;)</string>
							<key>name</key>
							<string>skript.color.9</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)a|\&lt;(light green|lime|lime green)\&gt;)</string>
							<key>name</key>
							<string>skript.color.a</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)b|\&lt;(light cyan|light aqua)\&gt;)</string>
							<key>name</key>
							<string>skript.color.b</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)c|\&lt;(pink|light red)\&gt;)</string>
							<key>name</key>
							<string>skript.color.c</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)d|\&lt;(magenta|light purple)\&gt;)</string>
							<key>name</key>
							<string>skript.color.d</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)e|\&lt;(yellow|light yellow)\&gt;)</string>
							<key>name</key>
							<string>skript.color.e</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)f|\&lt;white\&gt;)</string>
							<key>name</key>
							<string>skript.color.f</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)l|\&lt;(bold|b)\&gt;)</string>
							<key>name</key>
							<string>skript.color.l</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)o|\&lt;(italics|italic|i)\&gt;)</string>
							<key>name</key>
							<string>skript.color.o</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)n|\&lt;(underlined|underline|u)\&gt;)</string>
							<key>name</key>
							<string>skript.color.n</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)m|\&lt;(strikethrough|strike|s)\&gt;)</string>
							<key>name</key>
							<string>skript.color.m</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)k|\&lt;magic\&gt;)</string>
							<key>name</key>
							<string>skript.color.k</string>
						</dict>
						<dict>
							<key>match</key>
							<string>((&amp;|§)r|\&lt;(reset|r)\&gt;)</string>
							<key>name</key>
							<string>skript.color.r</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(ban|unban|ip(-| )ban|kick|kill|op|deop)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( by ip| by reason of | because( of|) | on account of | due to )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(send (message |)|message |broadcast |set )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( to | in )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(add|give|increase|set|make|remove( all| every|)|subtract|reduce|delete|clear|reset)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( by | from )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(dye|colo(u|)r|paint)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)((execute |)(the |)(player |console |)command|)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(let|make) (player|console) execute( (the |)command|)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(damage|heal|repair)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(wait|halt)( for|)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(drop)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)((dis|)enchant)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( with )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(equip|make)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( wear )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(create|make) (a |an |)(safe |fake |)explosion(( |)effect| (of|with) (force|strength|power)|)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(ignite|set fire to|set|light|extinguish|strike lightning|strike lightning effect)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( on fire )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(log)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( (to|in)( file(s|)|) )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(close(( the|) inventory( view|) (to|of|for))|)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(open|show|close)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(play)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( on | at )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)((un|)poison|cure)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( (from|of) poison)</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(apply( potion of|))( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( (potion |)((of |)tier |))</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(push|thrust)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( (at|with) (speed|velocity|force) )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)((dis|e)nable pvp( in|))( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(replace( all| every|))( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(un(\-|)shear)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(shoot|let|spawn|teleport)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( shoot )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(close|turn off|de(-|)activate|(toggle|switch( (the |)state of))|open|turn on|activate)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(grow|create|generate)( tree( of type|)|)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( tree )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(force|((eject|dismount) (any|the) |)passenger(s|) (of|from))( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(any|the(ir|)|his|her|) vehicle(s|)</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(ride| (dis|)mount | leave )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\#</string>
					<key>end</key>
					<string>\n</string>
					<key>name</key>
					<string>skript.comment</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\![^#\n]*</string>
							<key>name</key>
							<string>skript.comment.important</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>^(options|variables|aliases|import)(?=\:$)</string>
					<key>name</key>
					<string>skript.options</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\{</string>
					<key>end</key>
					<string>(\}|\n)</string>
					<key>name</key>
					<string>skript.variable</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(\*|\.|\:\:|\-)</string>
							<key>name</key>
							<string>skript.variable.borders</string>
						</dict>
						<dict>
							<key>match</key>
							<string>\%.*?\%</string>
							<key>name</key>
							<string>skript.variable.external</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(.*?)</string>
							<key>name</key>
							<string>skript.variable.text</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>at ((0|1|)[0-9](am|pm)|(0|1|2|)[0-9]:(0|1|2|3|4|5|)[0-9])( in [a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)bed enter(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(player |)enter(ing|)( a | )bed(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)bed leav(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)( player |)leav(e|ing)( a | )bed(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)block damage(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(block |)(min(e|ing)|break)( of [a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)bucket empty(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)( player |)empty(ing|)( a | )bucket(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)bucket fill(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)( player |)fill(ing|)( a |)bucket(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(| block )burn(|ing)(| of [a-zA-Z ]+)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)( block |)can build check(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)chat(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)chunk (generat|populat)(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)chunk load(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)chunk unload(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)((right|left)(-| )|)(mouse(-| )|)click(ing|)( on [a-zA-Z ]+( (with|using|holding) [a-zA-Z ]+|)|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)((right|left)(-| )|)(mouse(-| )|)click(ing|) (with|using|holding) ([a-zA-Z ]+ on [a-zA-Z ]+)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)combust(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>skript.text</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(on |)command( \".*\"|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(( |)player |)connect(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)((eat|drink)(ing|)|consum(e|ing))(( of|) [a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(( |)player |)craft(ing|)(( of|) [a-zA-Z ]+)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)creeper power(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)damag(e|ing)( of [a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)death( of [a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)dispens(e|ing)( (of |)[a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)drop(ing|)( (of |)[a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(e|)xp(erience|)( orb | )spawn(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)spawn of( a(n|)| )(e|)xp(erience|)( orb|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)explo(d(e|ing)|sion)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)explosion prime(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on block |block |)fad(e|ing)( (of |)[a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)first (join|login)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)fish(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on block |block |)flow(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)block mov(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on block |block |)form(ing|)( (of |)[a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)fuel burn(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)game( |)mode change( to (creative|survival|adventure))(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)grow( of (normal|regular|oak|pine|redwood|fir|spruce|acacia|dark oak|birch|jungle))(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)heal(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(food|hunger) (level|met(er|re)|bar) chang(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on block |block |)ignit(e|ion)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)tool break(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)break(ing|) ((a|the)|)tool(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)item spawn(ing|) ((of |)[a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)(login|logging in|join(ing|))(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)(kick|being kicked)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)leaves decay(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)level( change|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)lightning( strike|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(step|walk)(ing|)  (on|over) ([a-zA-Z ]+)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on block |block )physics(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)(pick( |)up|picking up)( (of |)[a-zA-Z ]+)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)pig( |)zap(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)piston extend(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)piston react(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on block |block |)(plac(e|ing)|build(ing|))( (of |)[a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)portal(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)portal create(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)portal enter(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)entering( a | )portal(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(step(ping|) on |)(a |)(pressure |)plate(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(trip|(step(ping|) on |)(a |)tripwire)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)projectile hit(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(quit(ting|)|disconnect(ing|)|log( |)out|logging out)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)redstone( current| current (chang(e|ing))|chang(e|ing))(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)region (enter|leave|exit)(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(enter|leav|exit)(ing|) of region(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)respawn(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on script |script |)(load|init|enable)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on script |script |)(unload|stop|disable)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on projectile |projectile |)shoot(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)sign (chang(e|)|edit)(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)(chang(e|)|edit)(ing|)( a|) sign(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(server|skript) (start|load|enable)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(server|skript) (stop|unload|disable)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on ore |ore |)smelt(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)smelt(ing|) of ore(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)toggl(e|ing) sneak(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)sneak toggl(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)spawn(ing|)( (of |)[a-zA-Z ]+|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on world |world |)spawn change(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)spread(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)toggl(e|ing) sprint(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)sprint toggl(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on entity |entity |)tam(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on entity |entity |)target(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on entity |entity |)un(-|)target(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)teleport(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)throw(ing|)( of|)( an|) egg(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player |player |)egg throw(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |on player(\'s|) |player(\'s|) |)(tool|item held|held item) chang(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)vehicle create(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)creat(e|ing|ion of)( a|) vehicle(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)vehicle damage(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)damag(e|ing)( a|) vehicle(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)vehicle destroy(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)destr(oy(ing|)|uction of)( a|) vehicle(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)vehicle enter(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)enter(ing|)( a|) vehicle(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)vehicle exit(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)exit(ing|)( a|) vehicle(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)weather change( to (clear|sunny|sun|rainy|raining|rain|thundering|thunderstorm|thunder)|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)world init(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)world load(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)world sav(e|ing)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)world unload(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)zombie break(ing|)( a|)( wood(en|)|) door(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)every ([a-z1-9 ]+) in (world(s|)|) ([a-zA-Z ]+)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)every ([a-z1-9 ]+)(\:)</string>
					<key>name</key>
					<string>skript.section</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(text(s|)|player(s|)|string(s|)|integer(s|)|number(s|)|offline( |)player(s|)|timespan|item(stack|(| )type|s|)|weather type|enchantment type|potion(| effect )type|entity type(s|)|livingentit(y|ies)|object(s|))</string>
					<key>name</key>
					<string>skript.commandargs</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(biome|block|boolean|chunk|click types?|colou?rs?|custom ?enchantments?|damage causes?|date|difficult(y|ies)|directions?|enchantments?|enchant(ing|ment) types?|experience|game ?modes?|gui ?inventor(y|ies)|inventory actions?|inventory types?|items?|materials?|living ?entit(y|ies)|locations?|metadata holders?|money|num(ber|)s?|objects?|offline ?players?|potion((| )effect)((| )type)s?|projectile?|recipe?|regions?|server ?icons?|slot ?types?|spawn(ing|) reasons?|teleport (cause|reason|type)s?|(text|string)s?|times?|time ?periods?|durations?|time ?spans?|tree ?types?|trees?|vectors?|(visual|particle) effects?|weather ?types?|weather conditions?|weathers?|worlds?)</string>
					<key>name</key>
					<string>skript.types</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s|\t)(description|usage|permission( message|)|executable by|aliases|trigger|cooldown( message| bypass| storage|))(?=\:)</string>
					<key>name</key>
					<string>skript.section.meta</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\d+|\bnow\b)</string>
					<key>name</key>
					<string>skript.numbers</string>
				</dict>
				<dict>
					<key>match</key>
					<string>true</string>
					<key>name</key>
					<string>skript.boolean.true</string>
				</dict>
				<dict>
					<key>match</key>
					<string>false</string>
					<key>name</key>
					<string>skript.boolean.false</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(stop( trigger| loop|)|(exit)|(escape)|((un|)cancel( | the )event))\b</string>
					<key>name</key>
					<string>skript.codestops</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)any( |)move(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)download(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(player |)edit book(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)enchant( item|)(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)horse jump(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)inventory click(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)inventory (open|close)(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(open|close) inventory(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)jump(ing|)(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)(server |)(list |)ping(\:)</string>
					<key>name</key>
					<string>skript.section.ws</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(open( virual| fake|) (anvil|furance) (to|for)( the|))( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(clear|wait(|a )|halt(|a ))</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(add|reduce|remove|hide|show|reveal)</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(minecraft |)(tick(s|)|second(s|)|minute(s|)|hour(s|)|day(s|)|year(s|))</string>
					<key>name</key>
					<string>skript.time</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(creative|survival|spectator|adventure|named|with name|with lore|parse(d|)|and|message|permission(s|)|colo(u|)red)\b</string>
					<key>name</key> 
					<string>skript.expressions</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((un|)glow(ing|))</string>
					<key>name</key>
					<string>skript.glowing</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(run)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( (command|cmd) | as op)</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(bungeecord connect)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(delete (file|folder)|df)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(download( from))( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( to file )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(create (file|folder))( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)(((dis|)allow|(dis|e)nable) (fly|flight) (for|to))( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s+|\t+)((set|change) slot in)( )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>( hand( bar|) to )</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(on |)any movement(\:)</string>
					<key>name</key>
					<string>skript.section.skquery</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\binventor(y|ies)\b</string>
					<key>name</key>
					<string>skript.expr.inventory</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(plural |)(effect|expression|condition)</string>
					<key>name</key>
					<string>skript.skriptmirror.effects</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^(\s*|\t*)(get|patterns|check|set|return(| type)|loop of|parse)(?=\:)</string>
					<key>name</key>
					<string>skript.skriptmirror.method</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\s+|\t+)\b(if|else if|else|while|loop(?!-)|return|continue)\b</string>
					<key>name</key>
					<string>skript.operator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\bfunction\b</string>
					<key>name</key>
					<string>skript.operator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^command </string>
					<key>name</key>
					<string>skript.command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(title|subtitle|action( |)bar|boss( |)bar)\b</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(^\t+|\s+)(play)\b</string>
					<key>name</key>
					<string>skript.effect</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.skript</string>
	<key>uuid</key>
	<string>bdf45b93-232e-475f-8783-cad8f0a82773</string>
</dict>
</plist>

